export const states = {
  'United States': [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ],
  Australia: [
    'New South Wales',
    'Victoria',
    'Queensland',
    'Western Australia',
    'South Australia',
    'Tasmania',
    'Australian Capital Territory',
    'Northern Territory',
  ],
  Brazil: [
    'Acre',
    'Alagoas',
    'Amapá',
    'Amazonas',
    'Bahia',
    'Ceará',
    'Distrito Federal',
    'Espírito Santo',
    'Goiás',
    'Maranhão',
    'Mato Grosso',
    'Mato Grosso do Sul',
    'Minas Gerais',
    'Pará',
    'Paraíba',
    'Paraná',
    'Pernambuco',
    'Piauí',
    'Rio de Janeiro',
    'Rio Grande do Norte',
    'Rio Grande do Sul',
    'Rondônia',
    'Roraima',
    'Santa Catarina',
    'São Paulo',
    'Sergipe',
    'Tocantins',
  ],
  Germany: [
    'Baden-Württemberg',
    'Bavaria',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hesse',
    'Lower Saxony',
    'Mecklenburg-Vorpommern',
    'North Rhine-Westphalia',
    'Rhineland-Palatinate',
    'Saarland',
    'Saxony',
    'Saxony-Anhalt',
    'Schleswig-Holstein',
    'Thuringia',
  ],
  India: [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
  ],
  Mexico: [
    'Aguascalientes',
    'Baja California',
    'Baja California Sur',
    'Campeche',
    'Coahuila',
    'Colima',
    'Chiapas',
    'Chihuahua',
    'Ciudad de México',
    'Durango',
    'Guanajuato',
    'Guerrero',
    'Hidalgo',
    'Jalisco',
    'México',
    'Michoacán',
    'Morelos',
    'Nayarit',
    'Nuevo León',
    'Oaxaca',
    'Puebla',
    'Querétaro',
    'Quintana Roo',
    'San Luis Potosí',
    'Sinaloa',
    'Sonora',
    'Tabasco',
    'Tamaulipas',
    'Tlaxcala',
    'Veracruz',
    'Yucatán',
    'Zacatecas',
  ],
  Canada: [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Nova Scotia',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
  ],
  China: [
    'Anhui',
    'Fujian',
    'Gansu',
    'Guangdong',
    'Guizhou',
    'Hainan',
    'Hebei',
    'Heilongjiang',
    'Henan',
    'Hubei',
    'Hunan',
    'Jiangsu',
    'Jiangxi',
    'Jilin',
    'Liaoning',
    'Qinghai',
    'Shaanxi',
    'Shandong',
    'Shanghai',
    'Shanxi',
    'Sichuan',
    'Tianjin',
    'Xinjiang',
    'Yunnan',
    'Zhejiang',
  ],
  Russia: [
    'Amur Oblast',
    'Arkhangelsk Oblast',
    'Astrakhan Oblast',
    'Belgorod Oblast',
    'Bryansk Oblast',
    'Chechen Republic',
    'Chelyabinsk Oblast',
    'Chukotka Autonomous Okrug',
    'Chuvash Republic',
    'Irkutsk Oblast',
    'Ivanovo Oblast',
    'Jewish Autonomous Oblast',
    'Kabardino-Balkar Republic',
    'Kaliningrad Oblast',
    'Kaluga Oblast',
    'Kamchatka Krai',
    'Karachay-Cherkess Republic',
    'Kemerovo Oblast',
    'Khabarovsk Krai',
    'Khanty-Mansi Autonomous Okrug',
    'Kirov Oblast',
    'Komi Republic',
    'Kostroma Oblast',
    'Krasnodar Krai',
    'Krasnoyarsk Krai',
    'Kurgan Oblast',
    'Kursk Oblast',
    'Leningrad Oblast',
    'Lipetsk Oblast',
    'Magadan Oblast',
    'Mari El Republic',
    'Moscow',
    'Moscow Oblast',
    'Murmansk Oblast',
    'Nenets Autonomous Okrug',
    'Nizhny Novgorod Oblast',
    'Novgorod Oblast',
    'Novosibirsk Oblast',
    'Omsk Oblast',
    'Orenburg Oblast',
    'Penza Oblast',
    'Perm Krai',
    'Primorsky Krai',
    'Pskov Oblast',
    'Rostov Oblast',
    'Ryazan Oblast',
    'Saint Petersburg',
    'Sakha Republic',
    'Sakhalin Oblast',
    'Samara Oblast',
    'Saratov Oblast',
    'Smolensk Oblast',
    'Stavropol Krai',
    'Sverdlovsk Oblast',
    'Tambov Oblast',
    'Tatarstan Republic',
    'Tomsk Oblast',
    'Tula Oblast',
    'Tver Oblast',
    'Tyumen Oblast',
    'Udmurt Republic',
    'Ulianovsk Oblast',
    'Ulyanovsk Oblast',
    'Vladimir Oblast',
    'Volgograd Oblast',
    'Vologda Oblast',
    'Voronezh Oblast',
    'Yamalo-Nenets Autonomous Okrug',
    'Yaroslavl Oblast',
    'Zabaykalsky Krai',
  ],
};
